[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[dependencies]

[dev-dependencies]
rand = "0.3"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "scanner"
path = "src/bin/scanner.rs"