[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[features]
default = []
cputrace = []
stacktrace = []

[dependencies]
bitflags = "0.3.3"
quick-error = "0.2.1"
sdl2 = "0.12"

[dev-dependencies]
rand = "0.3"

[[bin]]
name = "main"
path = "src/bin/main.rs"