[package]
name = "corrosion"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[features]
default = []
cputrace = []
stacktrace = []
mousepick = []

[dependencies]
bitflags = "0.5"
quick-error = "1.0"
sdl2 = "0.17"
blip_buf = "0.1.4"
memmap = "0.3"
clippy = "0.0.77"

[dev-dependencies]
sha1 = "0.2"
rand = "0.3"
