[package]
name = "corrosion"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[features]
default = []
cputrace = []
stacktrace = []

[dependencies]
bitflags = "0.4"
quick-error = "1.0"
sdl2 = "0.16"
stopwatch = "0.0.6"
blip_buf = "0.1.4"

[dev-dependencies]
rand = "0.3"

[profile.release]
lto = true

[[bin]]
name = "main"
path = "src/bin/main.rs"
