[package]
name = "corrosion-app"
version = "0.1.0"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[features]
mousepick = ["corrosion/mousepick"]

[dependencies]
corrosion = { path = "..", features = [] }
stopwatch = "0.0.7"

[profile.release]
#lto = true
#debug = true
